[tool.yapf]
indent_width = 2

[tool.basedpyright]
reportMissingTypeStubs = "none"
reportUnusedCallResult = "none"
reportUnknownArgumentType = "none"
reportUnknownMemberType = "none"
reportPrivateImportUsage = "none"
