#include "../global.hpp"

namespace supabase {
enum struct ErrorCodes {
  ANONYMOUS_PROVIDER_DISABLED = 0,
  BAD_CODE_VERIFIER,
  BAD_JSON,
  BAD_JWT,
  BAD_OAUTH_CALLBACK,
  BAD_OAUTH_STATE,
  CAPTCHA_FAILED,
  CONFLICT,
  EMAIL_ADDRESS_INVALID,
  EMAIL_ADDRESS_NOT_AUTHORIZED,
  EMAIL_CONFLICT_IDENTITY_NOT_DELETABLE,
  EMAIL_EXISTS,
  EMAIL_NOT_CONFIRMED,
  EMAIL_PROVIDER_DISABLED,
  FLOW_STATE_EXPIRED,
  FLOW_STATE_NOT_FOUND,
  HOOK_PAYLOAD_INVALID_CONTENT_TYPE,
  HOOK_PAYLOAD_OVER_SIZE_LIMIT,
  HOOK_TIMEOUT,
  HOOK_TIMEOUT_AFTER_RETRY,
  IDENTITY_ALREADY_EXISTS,
  IDENTITY_NOT_FOUND,
  INSUFFICIENT_AAL,
  INVITE_NOT_FOUND,
  INVALID_CREDENTIALS,
  MANUAL_LINKING_DISABLED,
  MFA_CHALLENGE_EXPIRED,
  MFA_FACTOR_NAME_CONFLICT,
  MFA_FACTOR_NOT_FOUND,
  MFA_IP_ADDRESS_MISMATCH,
  MFA_PHONE_ENROLL_NOT_ENABLED,
  MFA_PHONE_VERIFY_NOT_ENABLED,
  MFA_TOTP_ENROLL_NOT_ENABLED,
  MFA_TOTP_VERIFY_NOT_ENABLED,
  MFA_VERIFICATION_FAILED,
  MFA_VERIFICATION_REJECTED,
  MFA_VERIFIED_FACTOR_EXISTS,
  MFA_WEB_AUTHN_ENROLL_NOT_ENABLED,
  MFA_WEB_AUTHN_VERIFY_NOT_ENABLED,
  NO_AUTHORIZATION,
  NOT_ADMIN,
  OAUTH_PROVIDER_NOT_SUPPORTED,
  OTP_DISABLED,
  OTP_EXPIRED,
  OVER_EMAIL_SEND_RATE_LIMIT,
  OVER_REQUEST_RATE_LIMIT,
  OVER_SMS_SEND_RATE_LIMIT,
  PHONE_EXISTS,
  PHONE_NOT_CONFIRMED,
  PHONE_PROVIDER_DISABLED,
  PROVIDER_DISABLED,
  PROVIDER_EMAIL_NEEDS_VERIFICATION,
  REAUTHENTICATION_NEEDED,
  REAUTHENTICATION_NOT_VALID,
  REFRESH_TOKEN_NOT_FOUND,
  REFRESH_TOKEN_ALREADY_USED,
  REQUEST_TIMEOUT,
  SAME_PASSWORD,
  SAML_ASSERTION_NO_EMAIL,
  SAML_ASSERTION_NO_USER_ID,
  SAML_ENTITY_ID_MISMATCH,
  SAML_IDP_ALREADY_EXISTS,
  SAML_IDP_NOT_FOUND,
  SAML_METADATA_FETCH_FAILED,
  SAML_PROVIDER_DISABLED,
  SAML_RELAY_STATE_EXPIRED,
  SAML_RELAY_STATE_NOT_FOUND,
  SESSION_EXPIRED,
  SESSION_NOT_FOUND,
  SIGNUP_DISABLED,
  SINGLE_IDENTITY_NOT_DELETABLE,
  SMS_SEND_FAILED,
  SSO_DOMAIN_ALREADY_EXISTS,
  SSO_PROVIDER_NOT_FOUND,
  TOO_MANY_ENROLLED_MFA_FACTORS,
  UNEXPECTED_AUDIENCE,
  UNEXPECTED_FAILURE,
  USER_ALREADY_EXISTS,
  USER_BANNED,
  USER_NOT_FOUND,
  USER_SSO_MANAGED,
  VALIDATION_FAILED,
  WEAK_PASSWORD,
};

struct ErrorCode {
  ErrorCode() = default;
  ErrorCode(json error);

  int code;
  std::string error_code;
  std::string msg;

  ErrorCodes error;

  std::string get_description(ErrorCodes error_code);
private:
  static const std::map<ErrorCodes, std::string> error_code_descriptions;
  static const std::map<std::string, ErrorCodes> error_code_enums;
};
} // namespace supabase
